### ISSUE TITLE
complier error

### ISSUE THREAD

**Issue by AcSully** [shaneyuee/shmqueue#1]
shm_queue.c:859:40: error: ‘SQ_MAX_CONFLICT_TIME_MS’ undeclared (first use in this function); did you mean ‘SQ_MAX_CONFLICT_TRIES’?

**Comment by AcSully** [comment]
使用gcc -o sqtest -DSQ_FOR_TEST shm_queue.c

**Comment by shaneyuee** [comment]
> shm_queue.c:859:40: error: ‘SQ_MAX_CONFLICT_TIME_MS’ undeclared (first use in this function); did you mean ‘SQ_MAX_CONFLICT_TRIES’?

Sorry, I merged it from my local copy, forgetting to redefine this macro. It is now fixed.

**Comment by shaneyuee** [comment]
> 使用gcc -o sqtest -DSQ_FOR_TEST shm_queue.c

Thanks, updated.

**Comment by AcSully** [comment]
你好，

能说明一下如何进行测试么？我这边操作方法不对，会产生错误



***@***.***
 
From: Yu Zhenshen
Date: 2023-04-25 15:02
To: shaneyuee/shmqueue
CC: Niu; Author
Subject: Re: [shaneyuee/shmqueue] complier error (Issue #1)
使用gcc -o sqtest -DSQ_FOR_TEST shm_queue.c
Thanks, updated.

**Comment by AcSully** [comment]
能说明一下如何进行测试么？我这边操作方法不对，会产生错误。
另外，能看下你的sina邮箱么？
![image](https://user-images.githubusercontent.com/44167418/234215412-f229f89c-d35e-4e61-8538-3504a0a3b4bf.png)

**Comment by shaneyuee** [comment]
> 能说明一下如何进行测试么？我这边操作方法不对，会产生错误。
> 另外，能看下你的sina邮箱么？
> ![image](https://user-images.githubusercontent.com/44167418/234215412-f229f89c-d35e-4e61-8538-3504a0a3b4bf.png)

会不会没有/tmp目录的访问权限，不过不影响读写，fifo是用来通知读进程有数据到来的。可以起2个进程，一个put一个get，相互通信。

**Comment by AcSully** [comment]
请问高性能，实测800w/s以上是如何进行测试的呢？
